### ISSUE TITLE
Add a setting to consider if blocks

### ISSUE THREAD

**Issue by saledouble** [ponder-lab/Logging-Level-Evolution-Plugin#147]
Do not change a log level in a logging statement if there exists an immediate if statement whose condition contains a log level that matches the log level of the logging statement in question.

It looks like the log level in `if` block is closely related to the condition in `if` statement. Should we need to process log level in `if` block separately?

TODO: may need more examples, such as log wrapper.

**Comment by khatchad** [comment]
Do not change a log level in a logging statement if there exists an immediate if statement whose condition contains a log level that matches the log level of the logging statement in question.

**Comment by khatchad** [comment]
Once this is done, we can reissue https://github.com/JacpFX/JacpFX/pull/69 to prevent some of the wrapped logging statements from being incorrectly transformed.

**Comment by saledouble** [comment]
Fixed: bec3b19565e8e90ee38b1c13255e384a32f931a8

**Comment by khatchad** [comment]
From meeting: Remove the matching against the current level (just any level will do).

@saledouble Do you know why we wanted to match the levels?

**Comment by saledouble** [comment]
>Do you know why we wanted to match the levels?

@khatchad It is for keeping their logic. If log levels match, we could say they have their logic between these two log levels. If they don't match, there is no logic between them, i.e., the log level in `if condition` does not influence the log level in the following block. So we can treat its logging statement as a normal logging statement.

**Comment by saledouble** [comment]
Done: https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/commit/b1c7e453db1679c1733f6c6ff04cd068177bf176

**Comment by khatchad** [comment]
What's done?

**Comment by khatchad** [comment]
So the new change really just assumes that if the log statement is "guarded" by a condition mentioning a logging level, there must be *some* correlation?

**Comment by saledouble** [comment]
> What's done?

I have done some changes as you suggested in the last meeting: https://github.com/ponder-lab/ponder-lab.github.io/wiki/Meeting-on-March-6,-2019

**Comment by saledouble** [comment]
> So the new change really just assumes that if the log statement is "guarded" by a condition mentioning a logging level, there must be some correlation?

Yes.

**Comment by saledouble** [comment]
Can I close it?

**Comment by khatchad** [comment]
Yeah, I guess so. Have we updated the corresponding writing?

**Comment by saledouble** [comment]
>Have we updated the corresponding writing?

Yes.
