### ISSUE TITLE
NPE from getEnclosingType() in Evaluator

### ISSUE THREAD

**Issue by orenwf** [ponder-lab/Logging-Level-Evolution-Plugin#151]
Observed behavior:
- Null Pointer Exception at line 152 of `EvaluationHandler.java`

To re-create:
- import [ponder guava fork on branch fixed](https://github.com/ponder-lab/guava/tree/fixed)
- set environmental arguments `edu.cuny.hunter.log. evaluation.checkIfCondition=True` and `edu.cuny.hunter.log.evaluation.useGitHistory=True`
- create `eval.properties` with `NToUseForCommits=300`
- select projects: `guava`, `guava-gwt`, `guava-testlib`, `guava-tests`
- run `Evaluate Log Projects`

**Comment by khatchad** [comment]
Closing due to https://github.com/orenwf/Logging-Level-Evolution-Plugin/commit/c355930eac2b07b217ee62c83bddd5ae5a5b731b.

**Comment by khatchad** [comment]
Thanks for finding this @orenwf. Your reward is that you are assigned the issue :).
