### ISSUE TITLE
Normalize tables

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#154]
Need one of {`repos.csv`,`projects.csv`,`subjects.csv`} with a foreign key into `results.csv`. Information pertaining to repos (projects) should be moved from `results.csv` to the new CSV file.

**Comment by saledouble** [comment]
How about this:

```
CSVPrinter resultPrinter = Util.createCSVPrinter("result.csv",
	new String[] { "sequence", "subject", "repo URL", "input logging statements", "passing logging statements",
		"failures", "transformed logging statements", "average Java lines added",
		"average Java lines removed", "use log category (SEVERE/WARNING/CONFIG)",
		"use log category (CONFIG)", "not lower log levels of logs inside of catch blocks",
		"time (s)" });

CSVPrinter repoPrinter = Util.createCSVPrinter("repos.csv",
	new String[] { "repo URL", "SHA-1 of head", "N for commits",
		"actual number of commits"});
```

"repo URL" is a foreign key.

**Comment by khatchad** [comment]
Please use tables so I can read it.

**Comment by saledouble** [comment]
results.csv

sequence | subject | repo URL | input logging statements | passing logging statements | failures | transformed logging statements | average Java lines added | average Java lines removed | use log category (SEVERE/WARNING/CONFIG) | use log category (CONFIG) | not lower log levels of logs inside of catch   blocks | time (s)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1552232949927 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 1 | 5 | 0 | FALSE | FALSE | FALSE | 0.134
1552232950062 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 1 | 0 | 0 | FALSE | FALSE | TRUE | 0.149
1552232950211 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 1 | 0 | 0 | FALSE | TRUE | FALSE | 0.13
1552232950342 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 1 | 0 | 0 | FALSE | TRUE | TRUE | 0.154
1552232950497 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 1 | 0 | 0 | TRUE | FALSE | FALSE | 0.148
1552232950645 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 0 | 0 | 0 | TRUE | FALSE | TRUE | 0.157


repos.csv:

repo URL | SHA-1 of head | N for commits | actual number of commits
-- | -- | -- | --
https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 9aa4961f14d43ff6612c98a83b2ff8090435bb32 | 100 | 5
https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 9aa4961f14d43ff6612c98a83b2ff8090435bb32 | 100 | 5
https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 9aa4961f14d43ff6612c98a83b2ff8090435bb32 | 100 | 5
https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 9aa4961f14d43ff6612c98a83b2ff8090435bb32 | 100 | 5
https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 9aa4961f14d43ff6612c98a83b2ff8090435bb32 | 100 | 5
https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 9aa4961f14d43ff6612c98a83b2ff8090435bb32 | 100 | 5

**Comment by khatchad** [comment]
I guess that works. What do you think?

**Comment by khatchad** [comment]
You can it against your own code?

**Comment by saledouble** [comment]
>I guess that works. What do you think?

In repos, each line is for a running time. However, some information looks duplicate. I am not sure whether we need to remove duplication.

**Comment by saledouble** [comment]
>You can it against your own code?

Sorry, I am not very sure what you are meaning.

**Comment by khatchad** [comment]
I don't see any duplicates.

**Comment by khatchad** [comment]
But I think you need a sequence number in `repos.csv`

**Comment by saledouble** [comment]
>But I think you need a sequence number in repos.csv

I see. Yeah, so that we could know these rows are different.

**Comment by saledouble** [comment]
Add sequence: aa3db5a797989ec65f8a76876725ae70959e1191

**Comment by saledouble** [comment]
I think we don't need repo URL in `results.csv`, because `sequence` is a primary key.

**Comment by saledouble** [comment]
Should be something like this:

repos.csv:

sequence | repo URL | SHA-1 of head | N for commits | actual number of commits
-- | -- | -- | -- | --
1552324919028 | https://github.com/ponder-lab/JacpFX.git | 6b4cc6faaf68b04b99264f2ce9b7c75e2a76bd90 | 300 | 300
1552324919028 | https://github.com/ponder-lab/JacpFX.git | 300 | 0
1552324919028 | https://github.com/ponder-lab/JacpFX.git | 300 | 0
1552324919028 | https://github.com/ponder-lab/JacpFX.git | 300 | 0
1552324919028 | https://github.com/ponder-lab/JacpFX.git | 300 | 0
1552324919028 | https://github.com/ponder-lab/JacpFX.git | 300 | 0


results.csv:

sequence | subject | input logging statements | passing logging statements | failures | transformed logging statements | average Java lines added | average Java lines removed | use log category (SEVERE/WARNING/CONFIG) | use log category (CONFIG) | not lower log levels of logs inside of catch   blocks | time (s)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1552324919028 | jacpfx.API | 0 | 0 | 0 | 0 | 159 | 90 | FALSE | FALSE | FALSE | 91.843
1552324919028 | jacpfx.JavaFX | 22 | 22 | 0 | 14 | 0 | 0 | FALSE | FALSE | FALSE | 15.431
1552324919028 | jacpfx.JavaFXControls | 0 | 0 | 0 | 0 | 0 | 0 | FALSE | FALSE | FALSE | 11.159
1552324919028 | jacpfx.JavaFXLauncher | 0 | 0 | 0 | 0 | 0 | 0 | FALSE | FALSE | FALSE | 10.165
1552324919028 | jacpfx.JavaFXSpring | 0 | 0 | 0 | 0 | 0 | 0 | FALSE | FALSE | FALSE | 10.152
1552324919028 | JacpFXConcurrencyTools | 0 | 0 | 0 | 0 | 0 | 0 | FALSE | FALSE | FALSE | 0.971

**Comment by khatchad** [comment]
I would keep the repo URL there and use it as a UNIQUE index.

**Comment by khatchad** [comment]
It doesn't have to be completely normalized.

**Comment by khatchad** [comment]
Also, please only use the columns and not the rows to describe the schema so that it's more concise and easier to read.

**Comment by saledouble** [comment]
>I would keep the repo URL there and use it as a UNIQUE index.

I see.

**Comment by saledouble** [comment]
>Also, please only use the columns and not the rows to describe the schema so that it's more concise and easier to read.

OK.

**Comment by khatchad** [comment]
Columns "average Java lines added" and "average Java lines removed" are specific to repositories and not subprojects as far as I can tell. Thus, please move these columns to `repos.csv`.
