### ISSUE TITLE
Extra lines in repos.csv

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#157]
These lines should be removed (e.g., 3-7): <https://github.com/ponder-lab/Logging-Level-Evolution-Evaluation/blob/master/repos.csv#L3-L7>
<sub>[View in Slack](https://cunyponder.slack.com/archives/D94JKN0G4/p1552420639074400)</sub>

**Comment by khatchad** [comment]
What we can have here is extra duplicate lines. We can remove those in a post processing phase if necessary.

**Comment by saledouble** [comment]
This one is already fixed.
