### ISSUE TITLE
Is the active tasks' context destroyed prior to the tool running?

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#164]

**Comment by saledouble** [comment]
No, I will work on it.

**Comment by saledouble** [comment]
You have done this: a2ff1c4312b1e3678c7fc4fc95d37fdb339c0bfa

**Comment by saledouble** [comment]
The previous fix is not used by our plugin.

The actual location to clear context is here:
https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/blob/4ae6ffdadc611b80e940f40b0e622c35a8bacabb/edu.cuny.hunter.log.core/src/edu/cuny/hunter/log/core/refactorings/LogRejuvenatingProcessor.java#L235-L239

I did not assume that we have git history.

**Comment by khatchad** [comment]
Is this before or after the analysis?

**Comment by saledouble** [comment]
The fix is before the analysis. The previous solution is clearing task context after analysis.
