### ISSUE TITLE
Candidate logging statements change depending on the settings

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#195]
Add "candidate logging statements" column in result.csv and a new CSV file `candidate_log_invocations.csv` for candidates. The new CSV file must have a sequence number and columns that uniquely identify the logging statement (subject, log expression, start pos, type FQN, enclosing method). Other columns from `input_log_invocations.csv` are not necessary.

Roughly, the result structure of `result.csv` is as follows:

input logging statements | passing logging statements | failures | transformed logging statements | use log category (SEVERE/WARNING/CONFIG) | use log category (CONFIG)
-- | -- | -- | -- | -- | --

The problem is that if, for example, "use log category (SEVERE/WARNING/CONFIG)" is true, we don't consider, in our analysis and transformation, all of the "input logging statements." Rather, we only consider logging statements that are FINER, FINE, INFO, etc. Thus, when such settings are enabled, we need to know how many logging statements *can* be transformed.

Please add a new column "candidate logging statements" as follows:
1. If "use log category (SEVERE/WARNING/CONFIG)" and "use log category (CONFIG)" are both false, then "input logging statements" = "candidate logging statements".
1. If "use log category (CONFIG)" is false, then "candidate logging statements" **only** includes the "input logging statements" that are **not** CONFIG,.
1. If "use log category (SEVERE/WARNING/CONFIG)" is false, then "candidate logging statements" **only** includes the "input logging statements" that are **not** CONFIG, SEVERE, and WARNING.

The resulting structure should look something like this:

input logging statements | candidate logging statements | passing logging statements | failures | transformed logging statements
-- | -- | -- | -- | --

**Comment by saledouble** [comment]
Why we don't treat all settings are the same? i.e., why we don't consider settings of if condition and catch blocks for candidate log invocations?

**Comment by khatchad** [comment]
Because we are not excluding those logging statements. In those cases, we are altering the way we change the level. Does it make sense?

**Comment by saledouble** [comment]
>Because we are not excluding those logging statements. In those cases, we are altering the way we change the level. Does it make sense?

I see. I will change it.

**Comment by saledouble** [comment]
Do we need a separate CSV file for candidates?

**Comment by khatchad** [comment]
@saledouble Has this been completed?

**Comment by saledouble** [comment]
Yes.
