### ISSUE TITLE
Add support for slf4j

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#196]
Add support for the s4j logging framework, which is similar to `java.util.logging`. Many of the levels match directly.

**Comment by saledouble** [comment]
A fake PR after adding Slf4j support: https://github.com/ponder-lab/californium/pull/1
The Slf4j support is similar to J.U.L. support. I re-did the implementation and didn't use the one-to-one mapping from J.U.L to Slf4j.
