### ISSUE TITLE
What happens when this is method returns null?

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#202]
https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/blob/35cab4012aec01d7f2d14a366141b4371fa16c4a/edu.cuny.hunter.log.core/src/edu/cuny/hunter/log/core/utils/Util.java#L113

**Comment by saledouble** [comment]
The tool will do nothing. It returns null when the method binding cannot work or the declaring class is not Logger.

https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/blob/5b67adcbe042ba6e639ca042e000779a01c863a3/edu.cuny.hunter.log.core/src/edu/cuny/hunter/log/core/analysis/LogAnalyzer.java#L344-L361
