### ISSUE TITLE
Add setting to not lower logs with particular keywords in their messages

### ISSUE THREAD

**Issue by saledouble** [ponder-lab/Logging-Level-Evolution-Plugin#206]
Per jenkinsci/jenkins#4007, there are some logs that shouldn't be lowered. Some of them have words like "failed" and "disabled". We could also add "error" to that list. The comparison should be case insensitive. This is a precursor to #207.

 --Commented by @khatchad

**Comment by saledouble** [comment]
Do we need to count the number of log levels which are not transformed due to it?

**Comment by khatchad** [comment]
Also "exception."

**Comment by khatchad** [comment]
@saledouble Has this been completed?

**Comment by saledouble** [comment]
Yes.
