### ISSUE TITLE
Rerunning the evaluator causes a NPE

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#211]
```
May 07, 2019 8:41:16 AM edu.cuny.hunter.log.evaluation.handlers.EvaluationHandler lambda$0
INFO: Evaluation complete.

!ENTRY org.eclipse.core.jobs 4 2 2019-05-07 14:56:30.306
!MESSAGE An internal error occurred during: "Evaluating log level rejuventation ...".
!STACK 0
java.lang.NullPointerException
	at edu.cuny.hunter.log.evaluation.handlers.EvaluationHandler.lambda$0(EvaluationHandler.java:347)
	at org.eclipse.core.runtime.jobs.Job$1.run(Job.java:164)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by saledouble** [comment]
Line 347:

https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/blob/d2c3cc55093f7c78b91f1161c75660a07c60801b/edu.cuny.hunter.log.evalution/src/edu/cuny/hunter/log/evaluation/handlers/EvaluationHandler.java#L347

You need to close `result.csv` when you run the evaluator.

**Comment by khatchad** [comment]
The fix for this problem requires a code change.

**Comment by saledouble** [comment]
I am fixing it by adding if condition.

**Comment by khatchad** [comment]
https://github.com/ponder-lab/Optimize-Java-8-Streams-Refactoring/blob/a648cce999a36c698aef520e9d8ce516cd50301e/edu.cuny.hunter.streamrefactoring.eval/src/edu/cuny/hunter/streamrefactoring/eval/handlers/EvaluateConvertToParallelStreamRefactoringHandler.java#L599-L621
