### ISSUE TITLE
Cells with missing values in repos.csv

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#212]
These columns seem to be missing values. Is that because they aren't analyzing anything?:

average Java lines added | average Java lines removed
-- | --

More context:

sequence | repo URL | SHA-1 of head | N for commits | number of commits processed | actual number of commits | average Java lines added | average Java lines removed
-- | -- | -- | -- | -- | -- | -- | --
1557193610290 | https://github.com/bcgit/bc-java.git | d569f4bcf49612a17da482735a48f715e3727150 | 1000 | 1000 | 5561 | 110.978 | 39.414
1557193610290 | https://github.com/ponder-lab/CoreNLP.git | 5fdbfb209069276e95e1765093df9855d2cf2c38 | 1000 | 1000 | 15038 | 3290.226 | 3262.057
1557193610290 | https://github.com/DeviationTX/deviation-upload.git | 88751d6d7f082ec6649cbae4bb3dc2e717db60a3 | 1000 | 78 | 78 | 241.628205128205 | 76.4230769230769
1557193610290 | https://github.com/hms-dbmi/IRCT-API.git | aa0f039f454834e78affc94e159bb76a1ffefed1 | 1000 | 139 | 139 | 173.280575539568 | 70.7769784172662
1557193610290 | http://github.com/asad/ReactionDecoder.git | 032d919519eeb30153354020ea736cb18a6a7642 | 1000 | 571 | 571 | 1214.6112084063 | 743.183887915937
1557193610290 | https://github.com/ponder-lab/WALA.git | 590703b31a7b166bd6041926dd32c5e23bcb1314 | 1000 | 1000 | 6159 | 126.46 | 119.441
1557193610290 | git@github.com:ponder-lab/guava | f401df4e71894073aebb9096d47abd955aa9eb6d | 1000 | 1000 | 4862 | 510.92 | 121.851
1557193610290 | https://github.com/ponder-lab/jsilhouette.git | 517fc2b873602991898691e1c1f074428e7a6604 | 1000 | 29 | 29 | 154.137931034483 | 35.0689655172414
1557193610290 | https://github.com/jenkinsci/blueocean-plugin | 6e87cc0e76449669a942d66a9391cd7a46a943e0 | 1000 | 1000 | 4030 | 50.139 | 14.359
1557193610290 | https://github.com/JacpFX/JacpFX.git | 14c2a4c332c6d63f7d86d26b899011ca23715996 | 1000 | 365 | 365 | 227.054794520548 | 105.567123287671
1557193610290 | https://github.com/ponder-lab/spotbugs.git | 18c8dcb849d4a6d826ff9d185c7df42d3bb48de7 | 1000 | 1000 | 16067 | 26.565 | 61.135
1557193610290 | https://github.com/ponder-lab/jenkins.git | 44c4d3989232082c254d27ae360aa810669f44b7 | 1000 | 1000 | 28288 | 27.119 | 18.424
1557193610290 | https://github.com/ponder-lab/error-prone.git | fe2e3cc2cf1958cb7c487bfe89852bb4c225ba9d | 1000 | 1000 | 3672 | 88.687 | 31.416
1557193610290 | https://github.com/ponder-lab/selenium.git | 8389311401473048c215f0885dc5dc5488a311eb | 1000 | 1000 | 23812 | 30.311 | 15.343
1557193610290 | https://github.com/eclipse/californium.git | 0dd6db579be90c514dd765027ec55ed7a4668337 | 1000 | 968 | 968 | 188.242768595041 | 101.496900826446
1557193610290 | https://github.com/ponder-lab/hollow.git | 43ca100034a01050fb764170bd32b085ac9a3c22 | 1000 | 884 | 884 | 148.567873303167 | 29.2703619909502
1557193610290 | https://github.com/oracle/opengrok.git | d975631b4733b73d5a1a2e0cde12d2717cab99f3 | 1000 | 1000 | 4611 | 49.715 | 42.621
1557197752716 | https://github.com/bcgit/bc-java.git | d569f4bcf49612a17da482735a48f715e3727150 | 1000 | 1000 | 5561 | 110.978 | 39.414
1557197752716 | https://github.com/ponder-lab/CoreNLP.git | 5fdbfb209069276e95e1765093df9855d2cf2c38 | 1000 | 1000 | 15038 | 3290.226 | 3262.057
1557197752716 | https://github.com/DeviationTX/deviation-upload.git | 88751d6d7f082ec6649cbae4bb3dc2e717db60a3 | 1000 | 78 | 78 | 241.628205128205 | 76.4230769230769
1557197752716 | https://github.com/hms-dbmi/IRCT-API.git | aa0f039f454834e78affc94e159bb76a1ffefed1 | 1000 | 139 | 139 | 173.280575539568 | 70.7769784172662
1557197752716 | http://github.com/asad/ReactionDecoder.git | 032d919519eeb30153354020ea736cb18a6a7642 | 1000 | 571 | 571 | 1214.6112084063 | 743.183887915937
1557197752716 | https://github.com/ponder-lab/WALA.git | 590703b31a7b166bd6041926dd32c5e23bcb1314 | 1000 | 1000 | 6159 | 0 | 0
1557197752716 | git@github.com:ponder-lab/guava | f401df4e71894073aebb9096d47abd955aa9eb6d | 1000 | 1000 | 4862 | 0 | 0
1557197752716 | https://github.com/ponder-lab/jsilhouette.git | 517fc2b873602991898691e1c1f074428e7a6604 | 1000 | 29 | 29 | 0 | 0
1557197752716 | https://github.com/jenkinsci/blueocean-plugin | 6e87cc0e76449669a942d66a9391cd7a46a943e0 | 1000 | 1000 | 4030 | 0 | 0
1557197752716 | https://github.com/JacpFX/JacpFX.git | 14c2a4c332c6d63f7d86d26b899011ca23715996 | 1000 | 365 | 365 | 0 | 0
1557197752716 | https://github.com/ponder-lab/spotbugs.git | 18c8dcb849d4a6d826ff9d185c7df42d3bb48de7 | 1000 | 1000 | 16067 | 0 | 0
1557197752716 | https://github.com/ponder-lab/jenkins.git | 44c4d3989232082c254d27ae360aa810669f44b7 | 1000 | 1000 | 28288 | 0 | 0
1557197752716 | https://github.com/ponder-lab/error-prone.git | fe2e3cc2cf1958cb7c487bfe89852bb4c225ba9d | 1000 | 1000 | 3672 | 0 | 0
1557197752716 | https://github.com/ponder-lab/selenium.git | 8389311401473048c215f0885dc5dc5488a311eb | 1000 | 1000 | 23812 | 0 | 0
1557197752716 | https://github.com/eclipse/californium.git | 0dd6db579be90c514dd765027ec55ed7a4668337 | 1000 | 968 | 968 | 0 | 0
1557197752716 | https://github.com/ponder-lab/hollow.git | 43ca100034a01050fb764170bd32b085ac9a3c22 | 1000 | 884 | 884 | 0 | 0
1557197752716 | https://github.com/oracle/opengrok.git | d975631b4733b73d5a1a2e0cde12d2717cab99f3 | 1000 | 1000 | 4611 | 0 | 0

**Comment by saledouble** [comment]
This one needs debugging.

**Comment by saledouble** [comment]
Some elements in the two maps were removed after the first sequence.

https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/blob/d2c3cc55093f7c78b91f1161c75660a07c60801b/edu.cuny.hunter.log.evalution/src/edu/cuny/hunter/log/evaluation/handlers/EvaluationHandler.java#L320

Why?? I never wrote the code to remove the elements in the maps.

**Comment by saledouble** [comment]
I see the problem. This issue is for the repo with multiple subprojects. The elements in the two maps were replaced again and again due to multiple subprojects. The replacements should not happen. The data were cleared after memoization. The maps use the data after clearing.
