### ISSUE TITLE
Methods not analyzed should not be considered as candidates

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#231]
Methods that are not analyzed (because N is too small) should *not* get a DOI of 0. They should have *no* DOI. 0 is a valid DOI value, but since we haven't analyzed these methods, we can't say for sure that their DOI is 0. As such, methods with no git history should:

- [x] **Not** be considered for transformation. How can we transform them if we don't know their DOI?
- [x] **Not** be listed as *candidates* in `candidates.csv`.
- [x] **Not** be considered in boundary calculations.

**Comment by khatchad** [comment]
May be related (and contrary) to #123.

**Comment by saledouble** [comment]
Done. 261236683d27c88344dbd1a9ec6ad96fc7677f98

**Comment by saledouble** [comment]
This is the current results with the original decay (N = 24000):

[results_original_decay.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3591615/results_original_decay.zip)

In the previous results, the candidates' number is 54. For the new results, the candidates' number is 38. Hence, there is 16 enclosing methods which are never analyzed.

**Comment by khatchad** [comment]
How many commits are there total in the repositorY?

**Comment by saledouble** [comment]
>How many commits are there total in the repositorY?

23812. It looks that there is a bug here.

**Comment by saledouble** [comment]
I tracked one non-candidate method in the set of log invocations. I found that the method was never touched by the mylyngit tool. But I also found some methods with the same name were analyzed by the tool. For now, I am unsure whether the method is missed by the tool or the tool did wrong for file copy and file renaming.

**Comment by saledouble** [comment]
Maybe selenium is too large for debugging. I will try a smaller one.

**Comment by khatchad** [comment]
@saledouble Please merge this in and close this issue. Then, open a new issue regarding the difference in candidates between having the change and not having the change with the same N covering all commits. You can reference this issue there.
