### ISSUE TITLE
Slow down decay rate of enclosing methods

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#232]
Highly related to #224. In fact, this should have been fixed since #224 was merged. What happened? If #224 was merged, why do we have this problem still (or do we not)? What was the new decay rate there?

The decay rate may have to be tied to the project being analyzed, e.g., number of commits, SLOC.

**Comment by khatchad** [comment]
Highly related to #217.

**Comment by saledouble** [comment]
original decay /64
[results_decay_64.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3590753/results_decay_64.zip)

original decay:
[results_original_decay.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3590754/results_original_decay.zip)

**Comment by saledouble** [comment]
original decay/16:
[results_div_16.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3592207/results_div_16.zip)

original decay/32:
[results_div_32.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3592209/results_div_32.zip)

original decay/128:
[results_div_128.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3592211/results_div_128.zip)

**Comment by khatchad** [comment]
Please try 16 and 256 on:
- [ ] One medium subject.
- [ ] One small subject.

**Comment by saledouble** [comment]
I tried one small subject: reactiondecoder, but there is no candidate in the results. I need to find another one.

[Reaction_Decoder.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3602645/Reaction_Decoder.zip)

**Comment by saledouble** [comment]
This result below is interesting. So many candidates but no transformation.
[results_IRCT_API.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3611629/results_IRCT_API.zip)

**Comment by saledouble** [comment]
By looking at results for IRCT_API, I think we need to fix #236 before doing this. IRCT-API is a good small project for this issue.

**Comment by khatchad** [comment]
I don't think it makes any sense to work on this issue with #236 pending.

**Comment by khatchad** [comment]
Blocked on #236.
