### ISSUE TITLE
Try dividing the boundaries logarithmically

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#233]
The smallest bucket should be for `FINEST` while the largest should be for `INFO` or `FATAL` depending on the settings selected.

**Comment by saledouble** [comment]
May log base 10 is better than base 2/e?

**Comment by saledouble** [comment]
Original data:
[results_div_128.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3596827/results_div_128.zip)

Data after dividing the boundaries logarithmically (using the setting "do not consider SEVERE/WARNING/CONFIG"):
[results_log.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3596830/results_log.zip)

**Comment by saledouble** [comment]
Data after dividing the boundaries logarithmically (using the setting 0 (consider CONFIG/WARNING/SEVERE)):
[results_setting_2.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3597052/results_setting_2.zip)

**Comment by khatchad** [comment]
This is blocked on #232.
