### ISSUE TITLE
Problem with #185

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#236]
There is a problem with the change made per #185. Basically, we are missing the coverage of the DOI spectrum because we removed the last two intervals. What happens when a logging statement's enclosing method DOI value falls outside of the intervals in the boundaries?

**Comment by khatchad** [comment]
Things to try:
- [ ] Try reverting the change made for #185 because now we have a different decay rate. This may help alleviate the problem we were having before.
- [ ] Try adding the rest of the spectrum to the last bucket. That last one (`INFO`) becomes very large.

**Comment by khatchad** [comment]
For the first one, just remove the `IntStream` loop.

**Comment by saledouble** [comment]
This the result after reverting the change:

[results_revert.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3601923/results_revert.zip)

**Comment by saledouble** [comment]
This is the results after modifying the last bucket:

[results_last_boundary.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3602134/results_last_boundary.zip)

**Comment by khatchad** [comment]
- [ ] Try another benchmark.
- [ ] Try another setting.

**Comment by saledouble** [comment]
I've tried another benchmark IRCT-API.

**Comment by saledouble** [comment]
The chrome in this DELL computer has something wrong. I could not use some dropdown menus and attach files here. I will attach the results at home.

**Comment by saledouble** [comment]
IRCT-API using option 1 (reverting change):
[irct_api_log_option_1.tar.gz](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3643084/irct_api_log_option_1.tar.gz)

IRCT-API using option 2 (adjusting last bucket):
[irct_api_log_option2.tar.gz](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3643085/irct_api_log_option2.tar.gz)

**Comment by saledouble** [comment]
Selenium with option 1 + 6 settings:
[selenium_log_option_1.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3643893/selenium_log_option_1.zip)

**Comment by saledouble** [comment]
IRCT-API option 1 without log scale:
[IRCT_API_option_1_without_log_scale.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3644161/IRCT_API_option_1_without_log_scale.zip)

IRCT-API option 2 with log scale:
[IRCT_API_log_option_2_without_log_scale.zip](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/files/3644160/IRCT_API_log_option_2_without_log_scale.zip)

**Comment by khatchad** [comment]
We will go with option 1, effectively reverting #185.
