### ISSUE TITLE
Git repo reading errors should be propogated

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#245]
https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/blob/6d4ae91ddab0e09101f417ae95ecc5f5556ba1e4/edu.cuny.hunter.mylyngit.core/src/edu/cuny/hunter/mylyngit/core/analysis/GitHistoryAnalyzer.java#L445-L448

**Comment by saledouble** [comment]
Fixed: 4b02f22
