### ISSUE TITLE
Add dead and alive keywords?

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#246]
https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/blob/9bf8e0bb3faa474753432dd0d3be065ba4189789/edu.cuny.hunter.log.core/src/edu/cuny/hunter/log/core/analysis/LogAnalyzer.java#L73

**Comment by saledouble** [comment]
I think they should be added.

**Comment by saledouble** [comment]
Added: #247
